
spring:
  datasource:
#    jdbc-url: jdbc:sqlite:D:/zhuomian/毕业/node-manage/database/manage.db
#    driver-class-name: org.sqlite.JDBC
    jdbc-url: jdbc:postgresql://localhost:5432/manage?stringtype=unspecified
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver




# 注意BootNettyChannelInboundHandlerAdapter类中datagramPath 手动修改
# ScriptUtil 手动修改
tempPath: D:/zhuomian/毕业/node-manage/temp/
configPath: D:/zhuomian/毕业/node-manage/config/
picturePath: D:/zhuomian/毕业/node-manage/picture/
dataPath: D:/zhuomian/毕业/node-manage/data/
scriptConfigPath: D:/zhuomian/毕业/node-manage/scripts/
