

# 注意BootNettyChannelInboundHandlerAdapter类中datagramPath 手动修改
tempPath: D:/zhuomian/毕业/node-manage/temp/
configPath: D:/zhuomian/毕业/node-manage/config/
typingDataPath: D:/zhuomian/毕业/node-manage/typingData/
typingFilePath: D:/zhuomian/毕业/node-manage/typingFile/
picturePath: D:/zhuomian/毕业/node-manage/picture/
