spring:
  application:
    name: node-manage
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8888


thread-pool:
  core_pool_size: 5
  max_pool_size: 5
  queue_capacity: 99999
  prefix: t-pool-


mybatis:
  configuration:
    call-setters-on-nulls: true
